# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-F_gXotchs5zO06tAXEwF4JJfL7k0VwW
"""

pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

# Set page layout
st.set_page_config(page_title="Sri Lankan Exchange Rate Dashboard", layout="wide")

# Title
st.title("Sri Lankan Exchange Rate Analysis Dashboard")
st.caption("Dataset: HDX | Years: 1970 - 2022")

# Load the final, prepared dataset
@st.cache_data
def load_data():
    df = pd.read_csv('final_exchange_rates.csv')
    df['Date'] = pd.to_datetime(df['Date'])
    return df

df = load_data()

# Visualization 1: Exchange Rate Trend
st.subheader("Exchange Rate Trend Over Time")
fig1, ax1 = plt.subplots(figsize=(12, 6))
ax1.plot(df['Date'], df['Exchange_Rate'], color='skyblue', label='Exchange Rate')
ax1.set_xlabel("Date")
ax1.set_ylabel("Exchange Rate (LKR to USD)")
ax1.set_title("Exchange Rate Over Time")
ax1.grid(True)
ax1.legend()
st.pyplot(fig1)

# Visualization 2: Year-on-Year Change
st.subheader("Year-on-Year Change")
fig2, ax2 = plt.subplots(figsize=(10, 6))
ax2.plot(df['Date'], df['YoY_Change'], color='orange', label='YoY Change (%)')
ax2.set_xlabel("Date")
ax2.set_ylabel("YoY Change (%)")
ax2.set_title("Year-on-Year Change in Exchange Rate")
ax2.grid(True)
ax2.legend()
st.pyplot(fig2)

# Visualization 3: Rolling Average
st.subheader("12-Month Rolling Average")
fig3, ax3 = plt.subplots(figsize=(10, 6))
ax3.plot(df['Date'], df['Rolling_Avg'], color='green', label='12-Month Rolling Average')
ax3.set_xlabel("Date")
ax3.set_ylabel("Exchange Rate (LKR to USD)")
ax3.set_title("12-Month Rolling Average of Exchange Rate")
ax3.grid(True)
ax3.legend()
st.pyplot(fig3)

# Visualization 4: Correlation Interactive Scatter
st.subheader("Correlation Analysis")
x_axis = st.selectbox("X-axis", ['Exchange_Rate', 'YoY_Change', 'Rolling_Avg'])
y_axis = st.selectbox("Y-axis", ['Exchange_Rate', 'YoY_Change', 'Rolling_Avg'])
fig4, ax4 = plt.subplots(figsize=(8, 6))
ax4.scatter(df[x_axis], df[y_axis], color='purple', alpha=0.5)
ax4.set_xlabel(x_axis)
ax4.set_ylabel(y_axis)
ax4.set_title(f"Correlation between {x_axis} and {y_axis}")
st.pyplot(fig4)

# Info Section
st.subheader("Potential External Factors")
st.markdown("""
Exchange rate fluctuations can be influenced by multiple factors such as:
- Global oil prices
- Inflation differentials
- Trade balance
- Interest rate policies
- Political events or instability
Future iterations could integrate these data sources for deeper analysis.
""")

#Feature Engineering display
df['Date'] = pd.to_datetime(df['Date'])
df['Year_Month'] = df['Date'].dt.strftime('%Y-%m')
df['Year'] = df['Date'].dt.year
bins = [0, 50, 100, 150, 200, 300, 400]
labels = ['0-50', '50-100', '100-150', '150-200', '200-300', '300-400']
df['Exchange_Rate_Bin'] = pd.cut(df['Exchange_Rate'], bins=bins, labels=labels, right=False)

st.subheader("Preview of Dataset")
st.dataframe(df.head())