# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-F_gXotchs5zO06tAXEwF4JJfL7k0VwW
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

# Set page layout
st.set_page_config(page_title="Sri Lankan Exchange Rate Dashboard", layout="wide")

# Load the final, prepared dataset
@st.cache_data
def load_data():
    df = pd.read_csv('final_exchange_rates.csv')
    df['Date'] = pd.to_datetime(df['Date'])
    df['Year'] = df['Date'].dt.year
    df['Month'] = df['Date'].dt.month
    return df

df = load_data()

# Title
st.title("Sri Lankan Exchange Rate Analysis Dashboard")
st.caption("Dataset: HDX | Years: 1970 - 2022")

st.markdown('This dashboard visualizes the exchange rates of the Sri Lankan Rupee (LKR) over time.')

# Sidebar for year range selection
st.sidebar.header('Filter by Year')
min_year = int(df['Year'].min())
max_year = int(df['Year'].max())
year_range = st.sidebar.slider('Select Year Range', min_year, max_year, (min_year, max_year))

# Sidebar for monthly vs annual toggle
view_option = st.sidebar.radio('View by', ('Monthly', 'Annual'))

# Filtered data
filtered_df = df[(df['Year'] >= year_range[0]) & (df['Year'] <= year_range[1])]

# Plotting Exchange Rate Trends
st.header('Exchange Rate Trends')
if view_option == 'Monthly':
    st.line_chart(filtered_df.set_index('Date')['Exchange_Rate'])
else:
    annual_df = filtered_df.groupby('Year').mean(numeric_only=True).reset_index()
    st.line_chart(annual_df.set_index('Year')['Exchange_Rate'])

# Visualization 1: Exchange Rate Trend
st.subheader("Exchange Rate Trend Over Time")
fig1 = px.line(
    df, x='Date', y='Exchange_Rate',
    labels={'Exchange_Rate': 'Exchange Rate (LKR to USD)'},
    title='Exchange Rate Over Time',
    markers=True
)
st.plotly_chart(fig1, use_container_width=True)

# Visualization 2: Year-on-Year Change
st.subheader("Year-on-Year Change")
fig2 = px.line(
    df, x='Date', y='YoY_Change',
    labels={'YoY_Change': 'Year-on-Year Change (%)'},
    title='Year-on-Year Change in Exchange Rate',
    markers=True
)
st.plotly_chart(fig2, use_container_width=True)

# Visualization 3: Rolling Average
st.subheader("12-Month Rolling Average")
fig3 = px.line(
    df, x='Date', y='Rolling_Avg',
    labels={'Rolling_Avg': '12-Month Rolling Average'},
    title='12-Month Rolling Average of Exchange Rate',
    markers=True
)
st.plotly_chart(fig3, use_container_width=True)

# Visualization 4: The 2022 Economic Crisis
st.header('2022 Economic Crisis Highlight')
fig4, ax4 = plt.subplots(figsize=(10, 5))
ax4.plot(df['Date'], df['Exchange_Rate'], label='Exchange Rate')
ax4.axvline(pd.Timestamp('2022-01-01'), color='r', linestyle='--', label='2022 Crisis Start')
ax4.axvline(pd.Timestamp('2022-12-31'), color='r', linestyle='--', label='2022 Crisis End')
ax4.legend()
ax4.set_title('Sri Lankan Exchange Rates with 2022 Crisis Highlight')
ax4.set_xlabel('Date')
ax4.set_ylabel('Exchange Rate')
ax4.grid(True)
st.pyplot(fig4)

# Visualization 5: Correlation Interactive Scatter
st.subheader("Correlation Analysis")
x_axis = st.selectbox("X-axis", ['Exchange_Rate', 'YoY_Change', 'Rolling_Avg'])
y_axis = st.selectbox("Y-axis", ['Exchange_Rate', 'YoY_Change', 'Rolling_Avg'])
correlation = df[[x_axis, y_axis]].corr(method='pearson').iloc[0,1]
fig5, ax5 = plt.subplots(figsize=(8, 6))
ax5.scatter(df[x_axis], df[y_axis], color='purple', alpha=0.5)
ax5.set_xlabel(x_axis)
ax5.set_ylabel(y_axis)
ax5.set_title(f"Scatter Plot: {x_axis} vs {y_axis}")
ax5.grid(True)
st.pyplot(fig5)

# Show correlation value and interpretation
st.markdown(f"**Pearson Correlation Coefficient between {x_axis} and {y_axis}: {correlation:.2f}**")
if abs(correlation) < 0.3:
    strength = "weak or no correlation"
elif abs(correlation) < 0.7:
    strength = "moderate correlation"
else:
    strength = "strong correlation"
st.markdown(f"_This indicates a **{strength}** between {x_axis} and {y_axis}_")

# Info Section
st.subheader("Potential External Factors")
st.markdown("""
Exchange rate fluctuations can be influenced by multiple factors such as:
- Global oil prices
- Inflation differentials
- Trade balance
- Interest rate policies
- Political events or instability

Future iterations could integrate these data sources for deeper analysis.
""")

# Feature Engineering Display
df['Year_Month'] = df['Date'].dt.strftime('%Y-%m')
bins = [0, 50, 100, 150, 200, 300, 400]
labels = ['0-50', '50-100', '100-150', '150-200', '200-300', '300-400']
df['Exchange_Rate_Bin'] = pd.cut(df['Exchange_Rate'], bins=bins, labels=labels, right=False)

# Dataset preview
st.subheader("Preview of Dataset")
st.dataframe(df.head(50))
